import { readdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { fileURLToPath } from "node:url";
import type { QueryMetricsResult } from "../src/telemetry/tools.ts";
import { metricUnits } from "../src/telemetry/tools.ts";
import { telemetryCorpusId } from "./seed-d1.ts";

const projectRoot = fileURLToPath(new URL("../", import.meta.url));
const localD1Directory = resolve(
  projectRoot,
  ".wrangler/state/v3/d1/miniflare-D1DatabaseObject"
);
const outputPath = resolve(projectRoot, "src/fixtures/telemetry-series.ts");

const INTERVAL_MS = 60_000;
const ROUTE = "/products";
const METRICS = [
  "request_count",
  "cache_hit_rate",
  "cache_key_cardinality",
  "origin_request_count",
  "origin_error_rate",
  "response_latency_p99"
] as const;

type CorpusRow = { window_from_ms: number; window_to_ms: number };

type BucketRow = {
  bucket_ms: number;
  request_count: number;
  cache_hit_rate: number;
  cache_key_cardinality: number;
  origin_request_count: number;
  origin_error_rate: number;
  response_latency_p99: number;
};

type DeploymentRow = { version: string; deployed_at_ms: number };

/**
 * Mirrors the aggregation in queryMetrics so the fixture cannot drift from what
 * the tool layer would return for the same call. The generated series is the
 * design surface's only source of plotted numbers.
 */
const bucketQuery = `
  WITH scoped AS (
    SELECT r.*
    FROM request_telemetry r
    JOIN telemetry_corpora c ON c.id = r.corpus_id
    WHERE c.active = 1 AND c.status = 'ready'
      AND r.route = ?
      AND r.timestamp_ms >= ? AND r.timestamp_ms < ?
  ), ranked AS (
    SELECT
      *,
      CAST(timestamp_ms / ${INTERVAL_MS} AS INTEGER) * ${INTERVAL_MS} AS bucket_ms,
      ROW_NUMBER() OVER (
        PARTITION BY CAST(timestamp_ms / ${INTERVAL_MS} AS INTEGER) * ${INTERVAL_MS}
        ORDER BY response_latency_ms
      ) AS latency_rank,
      COUNT(*) OVER (
        PARTITION BY CAST(timestamp_ms / ${INTERVAL_MS} AS INTEGER) * ${INTERVAL_MS}
      ) AS bucket_count
    FROM scoped
  )
  SELECT
    bucket_ms,
    COUNT(*) AS request_count,
    ROUND(100.0 * SUM(cache_status = 'HIT') / COUNT(*), 2) AS cache_hit_rate,
    COUNT(DISTINCT cache_key) AS cache_key_cardinality,
    ROUND(SUM(origin_request) / (${INTERVAL_MS} / 60000.0), 2) AS origin_request_count,
    ROUND(100.0 * SUM(origin_request = 1 AND response_status >= 400) / COUNT(*), 2) AS origin_error_rate,
    MAX(
      CASE
        WHEN latency_rank = CAST((bucket_count * 99 + 99) / 100 AS INTEGER)
        THEN response_latency_ms
      END
    ) AS response_latency_p99
  FROM ranked
  GROUP BY bucket_ms
  ORDER BY bucket_ms ASC
`;

async function localDatabasePath(): Promise<string> {
  const entries = await readdir(localD1Directory);
  const database = entries.find((entry) => entry.endsWith(".sqlite"));
  if (!database) {
    throw new Error(
      `No local D1 database found in ${localD1Directory}. Run npm run telemetry:seed:local first.`
    );
  }
  return resolve(localD1Directory, database);
}

function readCorpusWindow(db: DatabaseSync): CorpusRow {
  const row = db
    .prepare(
      `SELECT window_from_ms, window_to_ms FROM telemetry_corpora
       WHERE id = ? AND active = 1 AND status = 'ready'`
    )
    .get(telemetryCorpusId) as CorpusRow | undefined;
  if (!row) {
    throw new Error(
      `Corpus ${telemetryCorpusId} is not seeded and active locally.`
    );
  }
  return row;
}

function buildResult(rows: BucketRow[], window: CorpusRow): QueryMetricsResult {
  return {
    from: new Date(window.window_from_ms).toISOString(),
    to: new Date(window.window_to_ms).toISOString(),
    interval: "1m",
    units: Object.fromEntries(
      METRICS.map((metric) => [metric, metricUnits[metric]])
    ),
    points: rows.map((row) => ({
      bucketStart: new Date(row.bucket_ms).toISOString(),
      bucketEnd: new Date(
        Math.min(row.bucket_ms + INTERVAL_MS, window.window_to_ms)
      ).toISOString(),
      values: Object.fromEntries(
        METRICS.map((metric) => [metric, Number(row[metric])])
      )
    }))
  };
}

function render(result: QueryMetricsResult, deployments: DeploymentRow[]) {
  const call = {
    tool: "query_metrics",
    input: {
      metrics: [...METRICS],
      from: result.from,
      to: result.to,
      interval: result.interval,
      filters: { route: ROUTE }
    }
  };

  return `// Generated by \`npm run fixtures:series\` from the seeded local D1 corpus
// ${telemetryCorpusId}. Do not edit by hand: every number the artifact plots
// comes from the same aggregation the query_metrics tool performs.
import type { QueryMetricsResult } from "../telemetry/tools";

export const productsSignalCall = ${JSON.stringify(call, null, 2)} as const;

export const productsSignalSeries: QueryMetricsResult = ${JSON.stringify(result, null, 2)};

export const deploymentMarkers = ${JSON.stringify(
    deployments.map((deployment) => ({
      version: deployment.version,
      at: new Date(deployment.deployed_at_ms).toISOString()
    })),
    null,
    2
  )} as const;
`;
}

async function main() {
  const db = new DatabaseSync(await localDatabasePath(), { readOnly: true });
  try {
    const window = readCorpusWindow(db);
    const rows = db
      .prepare(bucketQuery)
      .all(ROUTE, window.window_from_ms, window.window_to_ms) as BucketRow[];
    const deployments = db
      .prepare(
        `SELECT d.version, d.deployed_at_ms
         FROM deployment_telemetry d
         JOIN telemetry_corpora c ON c.id = d.corpus_id
         WHERE c.active = 1 AND c.status = 'ready'
         ORDER BY d.deployed_at_ms ASC`
      )
      .all() as DeploymentRow[];

    await writeFile(
      outputPath,
      render(buildResult(rows, window), deployments),
      "utf8"
    );
    console.log(
      `Wrote ${rows.length} ${ROUTE} buckets and ${deployments.length} deployment markers to src/fixtures/telemetry-series.ts`
    );
  } finally {
    db.close();
  }
}

await main();
