// Generated by `npm run fixtures:series` from the seeded local D1 corpus
// cache-key-session-regression:v1. Do not edit by hand: every number the artifact plots
// comes from the same aggregation the query_metrics tool performs.
import type { QueryMetricsResult } from "../telemetry/tools";

export const productsSignalCall = {
  tool: "query_metrics",
  input: {
    metrics: [
      "request_count",
      "cache_hit_rate",
      "cache_key_cardinality",
      "origin_request_count",
      "origin_error_rate",
      "response_latency_p99"
    ],
    from: "2026-08-26T14:00:00.000Z",
    to: "2026-08-26T16:00:00.000Z",
    interval: "1m",
    filters: {
      route: "/products"
    }
  }
} as const;

export const productsSignalSeries: QueryMetricsResult = {
  from: "2026-08-26T14:00:00.000Z",
  to: "2026-08-26T16:00:00.000Z",
  interval: "1m",
  units: {
    request_count: "requests",
    cache_hit_rate: "percent",
    cache_key_cardinality: "keys",
    origin_request_count: "requests_per_minute",
    origin_error_rate: "percent",
    response_latency_p99: "milliseconds"
  },
  points: [
    {
      bucketStart: "2026-08-26T14:00:00.000Z",
      bucketEnd: "2026-08-26T14:01:00.000Z",
      values: {
        request_count: 1112,
        cache_hit_rate: 90.47,
        cache_key_cardinality: 40,
        origin_request_count: 106,
        origin_error_rate: 0,
        response_latency_p99: 188
      }
    },
    {
      bucketStart: "2026-08-26T14:01:00.000Z",
      bucketEnd: "2026-08-26T14:02:00.000Z",
      values: {
        request_count: 1091,
        cache_hit_rate: 93.31,
        cache_key_cardinality: 40,
        origin_request_count: 73,
        origin_error_rate: 0,
        response_latency_p99: 184
      }
    },
    {
      bucketStart: "2026-08-26T14:02:00.000Z",
      bucketEnd: "2026-08-26T14:03:00.000Z",
      values: {
        request_count: 1108,
        cache_hit_rate: 92.87,
        cache_key_cardinality: 40,
        origin_request_count: 79,
        origin_error_rate: 0,
        response_latency_p99: 186
      }
    },
    {
      bucketStart: "2026-08-26T14:03:00.000Z",
      bucketEnd: "2026-08-26T14:04:00.000Z",
      values: {
        request_count: 1113,
        cache_hit_rate: 93.44,
        cache_key_cardinality: 40,
        origin_request_count: 73,
        origin_error_rate: 0,
        response_latency_p99: 186
      }
    },
    {
      bucketStart: "2026-08-26T14:04:00.000Z",
      bucketEnd: "2026-08-26T14:05:00.000Z",
      values: {
        request_count: 1117,
        cache_hit_rate: 94.36,
        cache_key_cardinality: 40,
        origin_request_count: 63,
        origin_error_rate: 0,
        response_latency_p99: 182
      }
    },
    {
      bucketStart: "2026-08-26T14:05:00.000Z",
      bucketEnd: "2026-08-26T14:06:00.000Z",
      values: {
        request_count: 1069,
        cache_hit_rate: 93.45,
        cache_key_cardinality: 40,
        origin_request_count: 70,
        origin_error_rate: 0,
        response_latency_p99: 179
      }
    },
    {
      bucketStart: "2026-08-26T14:06:00.000Z",
      bucketEnd: "2026-08-26T14:07:00.000Z",
      values: {
        request_count: 1109,
        cache_hit_rate: 93.78,
        cache_key_cardinality: 40,
        origin_request_count: 69,
        origin_error_rate: 0,
        response_latency_p99: 182
      }
    },
    {
      bucketStart: "2026-08-26T14:07:00.000Z",
      bucketEnd: "2026-08-26T14:08:00.000Z",
      values: {
        request_count: 1113,
        cache_hit_rate: 94.7,
        cache_key_cardinality: 40,
        origin_request_count: 59,
        origin_error_rate: 0,
        response_latency_p99: 185
      }
    },
    {
      bucketStart: "2026-08-26T14:08:00.000Z",
      bucketEnd: "2026-08-26T14:09:00.000Z",
      values: {
        request_count: 1550,
        cache_hit_rate: 92.58,
        cache_key_cardinality: 40,
        origin_request_count: 115,
        origin_error_rate: 0,
        response_latency_p99: 187
      }
    },
    {
      bucketStart: "2026-08-26T14:09:00.000Z",
      bucketEnd: "2026-08-26T14:10:00.000Z",
      values: {
        request_count: 1529,
        cache_hit_rate: 93.98,
        cache_key_cardinality: 40,
        origin_request_count: 92,
        origin_error_rate: 0,
        response_latency_p99: 184
      }
    },
    {
      bucketStart: "2026-08-26T14:10:00.000Z",
      bucketEnd: "2026-08-26T14:11:00.000Z",
      values: {
        request_count: 1544,
        cache_hit_rate: 94.11,
        cache_key_cardinality: 40,
        origin_request_count: 91,
        origin_error_rate: 0,
        response_latency_p99: 182
      }
    },
    {
      bucketStart: "2026-08-26T14:11:00.000Z",
      bucketEnd: "2026-08-26T14:12:00.000Z",
      values: {
        request_count: 1525,
        cache_hit_rate: 92.72,
        cache_key_cardinality: 40,
        origin_request_count: 111,
        origin_error_rate: 0,
        response_latency_p99: 188
      }
    },
    {
      bucketStart: "2026-08-26T14:12:00.000Z",
      bucketEnd: "2026-08-26T14:13:00.000Z",
      values: {
        request_count: 1092,
        cache_hit_rate: 94.69,
        cache_key_cardinality: 40,
        origin_request_count: 58,
        origin_error_rate: 0,
        response_latency_p99: 186
      }
    },
    {
      bucketStart: "2026-08-26T14:13:00.000Z",
      bucketEnd: "2026-08-26T14:14:00.000Z",
      values: {
        request_count: 1099,
        cache_hit_rate: 95,
        cache_key_cardinality: 40,
        origin_request_count: 55,
        origin_error_rate: 0,
        response_latency_p99: 186
      }
    },
    {
      bucketStart: "2026-08-26T14:14:00.000Z",
      bucketEnd: "2026-08-26T14:15:00.000Z",
      values: {
        request_count: 1108,
        cache_hit_rate: 92.78,
        cache_key_cardinality: 40,
        origin_request_count: 80,
        origin_error_rate: 0,
        response_latency_p99: 188
      }
    },
    {
      bucketStart: "2026-08-26T14:15:00.000Z",
      bucketEnd: "2026-08-26T14:16:00.000Z",
      values: {
        request_count: 1102,
        cache_hit_rate: 93.92,
        cache_key_cardinality: 40,
        origin_request_count: 67,
        origin_error_rate: 0,
        response_latency_p99: 180
      }
    },
    {
      bucketStart: "2026-08-26T14:16:00.000Z",
      bucketEnd: "2026-08-26T14:17:00.000Z",
      values: {
        request_count: 1109,
        cache_hit_rate: 92.43,
        cache_key_cardinality: 40,
        origin_request_count: 84,
        origin_error_rate: 0,
        response_latency_p99: 187
      }
    },
    {
      bucketStart: "2026-08-26T14:17:00.000Z",
      bucketEnd: "2026-08-26T14:18:00.000Z",
      values: {
        request_count: 1111,
        cache_hit_rate: 91.36,
        cache_key_cardinality: 40,
        origin_request_count: 96,
        origin_error_rate: 0,
        response_latency_p99: 187
      }
    },
    {
      bucketStart: "2026-08-26T14:18:00.000Z",
      bucketEnd: "2026-08-26T14:19:00.000Z",
      values: {
        request_count: 1087,
        cache_hit_rate: 94.02,
        cache_key_cardinality: 40,
        origin_request_count: 65,
        origin_error_rate: 0,
        response_latency_p99: 187
      }
    },
    {
      bucketStart: "2026-08-26T14:19:00.000Z",
      bucketEnd: "2026-08-26T14:20:00.000Z",
      values: {
        request_count: 1084,
        cache_hit_rate: 91.42,
        cache_key_cardinality: 40,
        origin_request_count: 93,
        origin_error_rate: 0,
        response_latency_p99: 187
      }
    },
    {
      bucketStart: "2026-08-26T14:20:00.000Z",
      bucketEnd: "2026-08-26T14:21:00.000Z",
      values: {
        request_count: 1103,
        cache_hit_rate: 17.32,
        cache_key_cardinality: 915,
        origin_request_count: 912,
        origin_error_rate: 14.69,
        response_latency_p99: 1806
      }
    },
    {
      bucketStart: "2026-08-26T14:21:00.000Z",
      bucketEnd: "2026-08-26T14:22:00.000Z",
      values: {
        request_count: 1109,
        cache_hit_rate: 19.12,
        cache_key_cardinality: 910,
        origin_request_count: 897,
        origin_error_rate: 13.26,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T14:22:00.000Z",
      bucketEnd: "2026-08-26T14:23:00.000Z",
      values: {
        request_count: 1115,
        cache_hit_rate: 16.68,
        cache_key_cardinality: 928,
        origin_request_count: 929,
        origin_error_rate: 16.05,
        response_latency_p99: 1809
      }
    },
    {
      bucketStart: "2026-08-26T14:23:00.000Z",
      bucketEnd: "2026-08-26T14:24:00.000Z",
      values: {
        request_count: 1102,
        cache_hit_rate: 19.24,
        cache_key_cardinality: 898,
        origin_request_count: 890,
        origin_error_rate: 12.7,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T14:24:00.000Z",
      bucketEnd: "2026-08-26T14:25:00.000Z",
      values: {
        request_count: 1107,
        cache_hit_rate: 17.71,
        cache_key_cardinality: 935,
        origin_request_count: 911,
        origin_error_rate: 14.54,
        response_latency_p99: 1801
      }
    },
    {
      bucketStart: "2026-08-26T14:25:00.000Z",
      bucketEnd: "2026-08-26T14:26:00.000Z",
      values: {
        request_count: 1108,
        cache_hit_rate: 17.33,
        cache_key_cardinality: 936,
        origin_request_count: 916,
        origin_error_rate: 14.98,
        response_latency_p99: 1804
      }
    },
    {
      bucketStart: "2026-08-26T14:26:00.000Z",
      bucketEnd: "2026-08-26T14:27:00.000Z",
      values: {
        request_count: 1052,
        cache_hit_rate: 17.87,
        cache_key_cardinality: 872,
        origin_request_count: 864,
        origin_error_rate: 10.84,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T14:27:00.000Z",
      bucketEnd: "2026-08-26T14:28:00.000Z",
      values: {
        request_count: 1087,
        cache_hit_rate: 18.49,
        cache_key_cardinality: 898,
        origin_request_count: 886,
        origin_error_rate: 12.51,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T14:28:00.000Z",
      bucketEnd: "2026-08-26T14:29:00.000Z",
      values: {
        request_count: 1071,
        cache_hit_rate: 17.74,
        cache_key_cardinality: 890,
        origin_request_count: 881,
        origin_error_rate: 12.23,
        response_latency_p99: 1805
      }
    },
    {
      bucketStart: "2026-08-26T14:29:00.000Z",
      bucketEnd: "2026-08-26T14:30:00.000Z",
      values: {
        request_count: 1108,
        cache_hit_rate: 19.4,
        cache_key_cardinality: 903,
        origin_request_count: 893,
        origin_error_rate: 12.91,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T14:30:00.000Z",
      bucketEnd: "2026-08-26T14:31:00.000Z",
      values: {
        request_count: 1122,
        cache_hit_rate: 21.93,
        cache_key_cardinality: 889,
        origin_request_count: 876,
        origin_error_rate: 11.23,
        response_latency_p99: 1804
      }
    },
    {
      bucketStart: "2026-08-26T14:31:00.000Z",
      bucketEnd: "2026-08-26T14:32:00.000Z",
      values: {
        request_count: 1116,
        cache_hit_rate: 18.01,
        cache_key_cardinality: 929,
        origin_request_count: 915,
        origin_error_rate: 14.78,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T14:32:00.000Z",
      bucketEnd: "2026-08-26T14:33:00.000Z",
      values: {
        request_count: 1122,
        cache_hit_rate: 18.63,
        cache_key_cardinality: 926,
        origin_request_count: 913,
        origin_error_rate: 14.53,
        response_latency_p99: 1806
      }
    },
    {
      bucketStart: "2026-08-26T14:33:00.000Z",
      bucketEnd: "2026-08-26T14:34:00.000Z",
      values: {
        request_count: 1090,
        cache_hit_rate: 18.81,
        cache_key_cardinality: 891,
        origin_request_count: 885,
        origin_error_rate: 12.39,
        response_latency_p99: 1803
      }
    },
    {
      bucketStart: "2026-08-26T14:34:00.000Z",
      bucketEnd: "2026-08-26T14:35:00.000Z",
      values: {
        request_count: 1085,
        cache_hit_rate: 19.08,
        cache_key_cardinality: 895,
        origin_request_count: 878,
        origin_error_rate: 11.8,
        response_latency_p99: 1805
      }
    },
    {
      bucketStart: "2026-08-26T14:35:00.000Z",
      bucketEnd: "2026-08-26T14:36:00.000Z",
      values: {
        request_count: 1091,
        cache_hit_rate: 16.13,
        cache_key_cardinality: 924,
        origin_request_count: 915,
        origin_error_rate: 15.12,
        response_latency_p99: 1809
      }
    },
    {
      bucketStart: "2026-08-26T14:36:00.000Z",
      bucketEnd: "2026-08-26T14:37:00.000Z",
      values: {
        request_count: 1113,
        cache_hit_rate: 17.52,
        cache_key_cardinality: 925,
        origin_request_count: 918,
        origin_error_rate: 15.09,
        response_latency_p99: 1805
      }
    },
    {
      bucketStart: "2026-08-26T14:37:00.000Z",
      bucketEnd: "2026-08-26T14:38:00.000Z",
      values: {
        request_count: 1118,
        cache_hit_rate: 17.08,
        cache_key_cardinality: 943,
        origin_request_count: 927,
        origin_error_rate: 15.83,
        response_latency_p99: 1803
      }
    },
    {
      bucketStart: "2026-08-26T14:38:00.000Z",
      bucketEnd: "2026-08-26T14:39:00.000Z",
      values: {
        request_count: 1066,
        cache_hit_rate: 17.17,
        cache_key_cardinality: 899,
        origin_request_count: 883,
        origin_error_rate: 12.48,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T14:39:00.000Z",
      bucketEnd: "2026-08-26T14:40:00.000Z",
      values: {
        request_count: 1096,
        cache_hit_rate: 15.97,
        cache_key_cardinality: 923,
        origin_request_count: 921,
        origin_error_rate: 15.6,
        response_latency_p99: 1805
      }
    },
    {
      bucketStart: "2026-08-26T14:40:00.000Z",
      bucketEnd: "2026-08-26T14:41:00.000Z",
      values: {
        request_count: 1110,
        cache_hit_rate: 17.57,
        cache_key_cardinality: 929,
        origin_request_count: 915,
        origin_error_rate: 14.86,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T14:41:00.000Z",
      bucketEnd: "2026-08-26T14:42:00.000Z",
      values: {
        request_count: 1077,
        cache_hit_rate: 16.99,
        cache_key_cardinality: 903,
        origin_request_count: 894,
        origin_error_rate: 13.37,
        response_latency_p99: 1804
      }
    },
    {
      bucketStart: "2026-08-26T14:42:00.000Z",
      bucketEnd: "2026-08-26T14:43:00.000Z",
      values: {
        request_count: 1104,
        cache_hit_rate: 16.39,
        cache_key_cardinality: 928,
        origin_request_count: 923,
        origin_error_rate: 15.67,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T14:43:00.000Z",
      bucketEnd: "2026-08-26T14:44:00.000Z",
      values: {
        request_count: 1092,
        cache_hit_rate: 18.32,
        cache_key_cardinality: 905,
        origin_request_count: 892,
        origin_error_rate: 13,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T14:44:00.000Z",
      bucketEnd: "2026-08-26T14:45:00.000Z",
      values: {
        request_count: 1102,
        cache_hit_rate: 16.7,
        cache_key_cardinality: 920,
        origin_request_count: 918,
        origin_error_rate: 15.25,
        response_latency_p99: 1806
      }
    },
    {
      bucketStart: "2026-08-26T14:45:00.000Z",
      bucketEnd: "2026-08-26T14:46:00.000Z",
      values: {
        request_count: 1101,
        cache_hit_rate: 18.35,
        cache_key_cardinality: 904,
        origin_request_count: 899,
        origin_error_rate: 13.53,
        response_latency_p99: 1798
      }
    },
    {
      bucketStart: "2026-08-26T14:46:00.000Z",
      bucketEnd: "2026-08-26T14:47:00.000Z",
      values: {
        request_count: 1059,
        cache_hit_rate: 17.75,
        cache_key_cardinality: 886,
        origin_request_count: 871,
        origin_error_rate: 11.43,
        response_latency_p99: 1803
      }
    },
    {
      bucketStart: "2026-08-26T14:47:00.000Z",
      bucketEnd: "2026-08-26T14:48:00.000Z",
      values: {
        request_count: 1109,
        cache_hit_rate: 17.85,
        cache_key_cardinality: 924,
        origin_request_count: 911,
        origin_error_rate: 14.52,
        response_latency_p99: 1804
      }
    },
    {
      bucketStart: "2026-08-26T14:48:00.000Z",
      bucketEnd: "2026-08-26T14:49:00.000Z",
      values: {
        request_count: 1094,
        cache_hit_rate: 15.63,
        cache_key_cardinality: 935,
        origin_request_count: 923,
        origin_error_rate: 15.81,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T14:49:00.000Z",
      bucketEnd: "2026-08-26T14:50:00.000Z",
      values: {
        request_count: 1115,
        cache_hit_rate: 16.05,
        cache_key_cardinality: 937,
        origin_request_count: 936,
        origin_error_rate: 16.68,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T14:50:00.000Z",
      bucketEnd: "2026-08-26T14:51:00.000Z",
      values: {
        request_count: 1094,
        cache_hit_rate: 18.56,
        cache_key_cardinality: 911,
        origin_request_count: 891,
        origin_error_rate: 12.89,
        response_latency_p99: 1805
      }
    },
    {
      bucketStart: "2026-08-26T14:51:00.000Z",
      bucketEnd: "2026-08-26T14:52:00.000Z",
      values: {
        request_count: 1106,
        cache_hit_rate: 18.08,
        cache_key_cardinality: 925,
        origin_request_count: 906,
        origin_error_rate: 14.1,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T14:52:00.000Z",
      bucketEnd: "2026-08-26T14:53:00.000Z",
      values: {
        request_count: 1088,
        cache_hit_rate: 17.46,
        cache_key_cardinality: 905,
        origin_request_count: 898,
        origin_error_rate: 13.6,
        response_latency_p99: 1806
      }
    },
    {
      bucketStart: "2026-08-26T14:53:00.000Z",
      bucketEnd: "2026-08-26T14:54:00.000Z",
      values: {
        request_count: 1091,
        cache_hit_rate: 19.43,
        cache_key_cardinality: 894,
        origin_request_count: 879,
        origin_error_rate: 11.82,
        response_latency_p99: 1802
      }
    },
    {
      bucketStart: "2026-08-26T14:54:00.000Z",
      bucketEnd: "2026-08-26T14:55:00.000Z",
      values: {
        request_count: 1093,
        cache_hit_rate: 18.66,
        cache_key_cardinality: 901,
        origin_request_count: 889,
        origin_error_rate: 12.72,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T14:55:00.000Z",
      bucketEnd: "2026-08-26T14:56:00.000Z",
      values: {
        request_count: 1103,
        cache_hit_rate: 18.4,
        cache_key_cardinality: 912,
        origin_request_count: 900,
        origin_error_rate: 13.6,
        response_latency_p99: 1805
      }
    },
    {
      bucketStart: "2026-08-26T14:56:00.000Z",
      bucketEnd: "2026-08-26T14:57:00.000Z",
      values: {
        request_count: 1085,
        cache_hit_rate: 19.54,
        cache_key_cardinality: 900,
        origin_request_count: 873,
        origin_error_rate: 11.34,
        response_latency_p99: 1805
      }
    },
    {
      bucketStart: "2026-08-26T14:57:00.000Z",
      bucketEnd: "2026-08-26T14:58:00.000Z",
      values: {
        request_count: 1118,
        cache_hit_rate: 18.96,
        cache_key_cardinality: 918,
        origin_request_count: 906,
        origin_error_rate: 13.95,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T14:58:00.000Z",
      bucketEnd: "2026-08-26T14:59:00.000Z",
      values: {
        request_count: 1087,
        cache_hit_rate: 19.23,
        cache_key_cardinality: 885,
        origin_request_count: 878,
        origin_error_rate: 11.78,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T14:59:00.000Z",
      bucketEnd: "2026-08-26T15:00:00.000Z",
      values: {
        request_count: 1115,
        cache_hit_rate: 17.22,
        cache_key_cardinality: 931,
        origin_request_count: 923,
        origin_error_rate: 15.52,
        response_latency_p99: 1806
      }
    },
    {
      bucketStart: "2026-08-26T15:00:00.000Z",
      bucketEnd: "2026-08-26T15:01:00.000Z",
      values: {
        request_count: 1090,
        cache_hit_rate: 17.98,
        cache_key_cardinality: 909,
        origin_request_count: 894,
        origin_error_rate: 13.21,
        response_latency_p99: 1802
      }
    },
    {
      bucketStart: "2026-08-26T15:01:00.000Z",
      bucketEnd: "2026-08-26T15:02:00.000Z",
      values: {
        request_count: 1124,
        cache_hit_rate: 18.59,
        cache_key_cardinality: 928,
        origin_request_count: 915,
        origin_error_rate: 14.68,
        response_latency_p99: 1806
      }
    },
    {
      bucketStart: "2026-08-26T15:02:00.000Z",
      bucketEnd: "2026-08-26T15:03:00.000Z",
      values: {
        request_count: 1113,
        cache_hit_rate: 17.79,
        cache_key_cardinality: 934,
        origin_request_count: 915,
        origin_error_rate: 14.82,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T15:03:00.000Z",
      bucketEnd: "2026-08-26T15:04:00.000Z",
      values: {
        request_count: 1119,
        cache_hit_rate: 18.14,
        cache_key_cardinality: 921,
        origin_request_count: 916,
        origin_error_rate: 14.83,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:04:00.000Z",
      bucketEnd: "2026-08-26T15:05:00.000Z",
      values: {
        request_count: 1149,
        cache_hit_rate: 18.19,
        cache_key_cardinality: 951,
        origin_request_count: 940,
        origin_error_rate: 16.54,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T15:05:00.000Z",
      bucketEnd: "2026-08-26T15:06:00.000Z",
      values: {
        request_count: 1116,
        cache_hit_rate: 18.1,
        cache_key_cardinality: 926,
        origin_request_count: 914,
        origin_error_rate: 14.7,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T15:06:00.000Z",
      bucketEnd: "2026-08-26T15:07:00.000Z",
      values: {
        request_count: 1115,
        cache_hit_rate: 17.31,
        cache_key_cardinality: 936,
        origin_request_count: 922,
        origin_error_rate: 15.43,
        response_latency_p99: 1806
      }
    },
    {
      bucketStart: "2026-08-26T15:07:00.000Z",
      bucketEnd: "2026-08-26T15:08:00.000Z",
      values: {
        request_count: 1128,
        cache_hit_rate: 16.13,
        cache_key_cardinality: 955,
        origin_request_count: 946,
        origin_error_rate: 17.38,
        response_latency_p99: 1806
      }
    },
    {
      bucketStart: "2026-08-26T15:08:00.000Z",
      bucketEnd: "2026-08-26T15:09:00.000Z",
      values: {
        request_count: 1069,
        cache_hit_rate: 16.84,
        cache_key_cardinality: 899,
        origin_request_count: 889,
        origin_error_rate: 13,
        response_latency_p99: 1805
      }
    },
    {
      bucketStart: "2026-08-26T15:09:00.000Z",
      bucketEnd: "2026-08-26T15:10:00.000Z",
      values: {
        request_count: 1129,
        cache_hit_rate: 18.07,
        cache_key_cardinality: 926,
        origin_request_count: 925,
        origin_error_rate: 15.5,
        response_latency_p99: 1804
      }
    },
    {
      bucketStart: "2026-08-26T15:10:00.000Z",
      bucketEnd: "2026-08-26T15:11:00.000Z",
      values: {
        request_count: 1119,
        cache_hit_rate: 16.53,
        cache_key_cardinality: 939,
        origin_request_count: 934,
        origin_error_rate: 16.44,
        response_latency_p99: 1809
      }
    },
    {
      bucketStart: "2026-08-26T15:11:00.000Z",
      bucketEnd: "2026-08-26T15:12:00.000Z",
      values: {
        request_count: 1129,
        cache_hit_rate: 17.27,
        cache_key_cardinality: 951,
        origin_request_count: 934,
        origin_error_rate: 16.3,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:12:00.000Z",
      bucketEnd: "2026-08-26T15:13:00.000Z",
      values: {
        request_count: 1112,
        cache_hit_rate: 20.68,
        cache_key_cardinality: 903,
        origin_request_count: 882,
        origin_error_rate: 11.87,
        response_latency_p99: 1802
      }
    },
    {
      bucketStart: "2026-08-26T15:13:00.000Z",
      bucketEnd: "2026-08-26T15:14:00.000Z",
      values: {
        request_count: 1089,
        cache_hit_rate: 17.08,
        cache_key_cardinality: 909,
        origin_request_count: 903,
        origin_error_rate: 14.05,
        response_latency_p99: 1804
      }
    },
    {
      bucketStart: "2026-08-26T15:14:00.000Z",
      bucketEnd: "2026-08-26T15:15:00.000Z",
      values: {
        request_count: 1069,
        cache_hit_rate: 15.9,
        cache_key_cardinality: 906,
        origin_request_count: 899,
        origin_error_rate: 13.94,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T15:15:00.000Z",
      bucketEnd: "2026-08-26T15:16:00.000Z",
      values: {
        request_count: 1096,
        cache_hit_rate: 18.7,
        cache_key_cardinality: 905,
        origin_request_count: 891,
        origin_error_rate: 12.86,
        response_latency_p99: 1804
      }
    },
    {
      bucketStart: "2026-08-26T15:16:00.000Z",
      bucketEnd: "2026-08-26T15:17:00.000Z",
      values: {
        request_count: 1114,
        cache_hit_rate: 18.13,
        cache_key_cardinality: 927,
        origin_request_count: 912,
        origin_error_rate: 14.54,
        response_latency_p99: 1805
      }
    },
    {
      bucketStart: "2026-08-26T15:17:00.000Z",
      bucketEnd: "2026-08-26T15:18:00.000Z",
      values: {
        request_count: 1116,
        cache_hit_rate: 20.16,
        cache_key_cardinality: 907,
        origin_request_count: 891,
        origin_error_rate: 12.63,
        response_latency_p99: 1803
      }
    },
    {
      bucketStart: "2026-08-26T15:18:00.000Z",
      bucketEnd: "2026-08-26T15:19:00.000Z",
      values: {
        request_count: 1095,
        cache_hit_rate: 17.72,
        cache_key_cardinality: 913,
        origin_request_count: 901,
        origin_error_rate: 13.79,
        response_latency_p99: 1806
      }
    },
    {
      bucketStart: "2026-08-26T15:19:00.000Z",
      bucketEnd: "2026-08-26T15:20:00.000Z",
      values: {
        request_count: 1104,
        cache_hit_rate: 17.03,
        cache_key_cardinality: 924,
        origin_request_count: 916,
        origin_error_rate: 15.04,
        response_latency_p99: 1806
      }
    },
    {
      bucketStart: "2026-08-26T15:20:00.000Z",
      bucketEnd: "2026-08-26T15:21:00.000Z",
      values: {
        request_count: 1113,
        cache_hit_rate: 17.43,
        cache_key_cardinality: 933,
        origin_request_count: 919,
        origin_error_rate: 15.18,
        response_latency_p99: 1809
      }
    },
    {
      bucketStart: "2026-08-26T15:21:00.000Z",
      bucketEnd: "2026-08-26T15:22:00.000Z",
      values: {
        request_count: 1108,
        cache_hit_rate: 16.88,
        cache_key_cardinality: 931,
        origin_request_count: 921,
        origin_error_rate: 15.43,
        response_latency_p99: 1805
      }
    },
    {
      bucketStart: "2026-08-26T15:22:00.000Z",
      bucketEnd: "2026-08-26T15:23:00.000Z",
      values: {
        request_count: 1090,
        cache_hit_rate: 17.16,
        cache_key_cardinality: 910,
        origin_request_count: 903,
        origin_error_rate: 14.04,
        response_latency_p99: 1803
      }
    },
    {
      bucketStart: "2026-08-26T15:23:00.000Z",
      bucketEnd: "2026-08-26T15:24:00.000Z",
      values: {
        request_count: 1055,
        cache_hit_rate: 19.24,
        cache_key_cardinality: 860,
        origin_request_count: 852,
        origin_error_rate: 9.67,
        response_latency_p99: 1802
      }
    },
    {
      bucketStart: "2026-08-26T15:24:00.000Z",
      bucketEnd: "2026-08-26T15:25:00.000Z",
      values: {
        request_count: 1105,
        cache_hit_rate: 18.46,
        cache_key_cardinality: 916,
        origin_request_count: 901,
        origin_error_rate: 13.67,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:25:00.000Z",
      bucketEnd: "2026-08-26T15:26:00.000Z",
      values: {
        request_count: 1096,
        cache_hit_rate: 21.81,
        cache_key_cardinality: 874,
        origin_request_count: 857,
        origin_error_rate: 9.76,
        response_latency_p99: 1801
      }
    },
    {
      bucketStart: "2026-08-26T15:26:00.000Z",
      bucketEnd: "2026-08-26T15:27:00.000Z",
      values: {
        request_count: 1097,
        cache_hit_rate: 16.86,
        cache_key_cardinality: 929,
        origin_request_count: 912,
        origin_error_rate: 14.77,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:27:00.000Z",
      bucketEnd: "2026-08-26T15:28:00.000Z",
      values: {
        request_count: 1086,
        cache_hit_rate: 17.86,
        cache_key_cardinality: 903,
        origin_request_count: 892,
        origin_error_rate: 13.08,
        response_latency_p99: 1805
      }
    },
    {
      bucketStart: "2026-08-26T15:28:00.000Z",
      bucketEnd: "2026-08-26T15:29:00.000Z",
      values: {
        request_count: 1108,
        cache_hit_rate: 17.69,
        cache_key_cardinality: 917,
        origin_request_count: 912,
        origin_error_rate: 14.62,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T15:29:00.000Z",
      bucketEnd: "2026-08-26T15:30:00.000Z",
      values: {
        request_count: 1111,
        cache_hit_rate: 16.11,
        cache_key_cardinality: 940,
        origin_request_count: 932,
        origin_error_rate: 16.38,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T15:30:00.000Z",
      bucketEnd: "2026-08-26T15:31:00.000Z",
      values: {
        request_count: 1109,
        cache_hit_rate: 17.85,
        cache_key_cardinality: 919,
        origin_request_count: 911,
        origin_error_rate: 14.52,
        response_latency_p99: 1806
      }
    },
    {
      bucketStart: "2026-08-26T15:31:00.000Z",
      bucketEnd: "2026-08-26T15:32:00.000Z",
      values: {
        request_count: 1078,
        cache_hit_rate: 17.16,
        cache_key_cardinality: 896,
        origin_request_count: 893,
        origin_error_rate: 13.27,
        response_latency_p99: 1805
      }
    },
    {
      bucketStart: "2026-08-26T15:32:00.000Z",
      bucketEnd: "2026-08-26T15:33:00.000Z",
      values: {
        request_count: 1099,
        cache_hit_rate: 14.92,
        cache_key_cardinality: 939,
        origin_request_count: 935,
        origin_error_rate: 16.83,
        response_latency_p99: 1809
      }
    },
    {
      bucketStart: "2026-08-26T15:33:00.000Z",
      bucketEnd: "2026-08-26T15:34:00.000Z",
      values: {
        request_count: 1097,
        cache_hit_rate: 16.32,
        cache_key_cardinality: 926,
        origin_request_count: 918,
        origin_error_rate: 15.31,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:34:00.000Z",
      bucketEnd: "2026-08-26T15:35:00.000Z",
      values: {
        request_count: 1120,
        cache_hit_rate: 17.68,
        cache_key_cardinality: 926,
        origin_request_count: 922,
        origin_error_rate: 15.36,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T15:35:00.000Z",
      bucketEnd: "2026-08-26T15:36:00.000Z",
      values: {
        request_count: 1064,
        cache_hit_rate: 18.61,
        cache_key_cardinality: 884,
        origin_request_count: 866,
        origin_error_rate: 10.9,
        response_latency_p99: 1798
      }
    },
    {
      bucketStart: "2026-08-26T15:36:00.000Z",
      bucketEnd: "2026-08-26T15:37:00.000Z",
      values: {
        request_count: 1128,
        cache_hit_rate: 18.17,
        cache_key_cardinality: 938,
        origin_request_count: 923,
        origin_error_rate: 15.34,
        response_latency_p99: 1806
      }
    },
    {
      bucketStart: "2026-08-26T15:37:00.000Z",
      bucketEnd: "2026-08-26T15:38:00.000Z",
      values: {
        request_count: 1114,
        cache_hit_rate: 16.25,
        cache_key_cardinality: 934,
        origin_request_count: 933,
        origin_error_rate: 16.43,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:38:00.000Z",
      bucketEnd: "2026-08-26T15:39:00.000Z",
      values: {
        request_count: 1111,
        cache_hit_rate: 17.01,
        cache_key_cardinality: 929,
        origin_request_count: 922,
        origin_error_rate: 15.48,
        response_latency_p99: 1805
      }
    },
    {
      bucketStart: "2026-08-26T15:39:00.000Z",
      bucketEnd: "2026-08-26T15:40:00.000Z",
      values: {
        request_count: 1086,
        cache_hit_rate: 17.96,
        cache_key_cardinality: 892,
        origin_request_count: 891,
        origin_error_rate: 12.98,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T15:40:00.000Z",
      bucketEnd: "2026-08-26T15:41:00.000Z",
      values: {
        request_count: 1118,
        cache_hit_rate: 17.62,
        cache_key_cardinality: 929,
        origin_request_count: 921,
        origin_error_rate: 15.3,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:41:00.000Z",
      bucketEnd: "2026-08-26T15:42:00.000Z",
      values: {
        request_count: 1111,
        cache_hit_rate: 18.99,
        cache_key_cardinality: 905,
        origin_request_count: 900,
        origin_error_rate: 13.5,
        response_latency_p99: 1806
      }
    },
    {
      bucketStart: "2026-08-26T15:42:00.000Z",
      bucketEnd: "2026-08-26T15:43:00.000Z",
      values: {
        request_count: 1119,
        cache_hit_rate: 18.68,
        cache_key_cardinality: 919,
        origin_request_count: 910,
        origin_error_rate: 14.3,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:43:00.000Z",
      bucketEnd: "2026-08-26T15:44:00.000Z",
      values: {
        request_count: 1065,
        cache_hit_rate: 18.69,
        cache_key_cardinality: 877,
        origin_request_count: 866,
        origin_error_rate: 10.89,
        response_latency_p99: 1801
      }
    },
    {
      bucketStart: "2026-08-26T15:44:00.000Z",
      bucketEnd: "2026-08-26T15:45:00.000Z",
      values: {
        request_count: 1128,
        cache_hit_rate: 18.88,
        cache_key_cardinality: 928,
        origin_request_count: 915,
        origin_error_rate: 14.63,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:45:00.000Z",
      bucketEnd: "2026-08-26T15:46:00.000Z",
      values: {
        request_count: 1108,
        cache_hit_rate: 18.86,
        cache_key_cardinality: 916,
        origin_request_count: 899,
        origin_error_rate: 13.45,
        response_latency_p99: 1805
      }
    },
    {
      bucketStart: "2026-08-26T15:46:00.000Z",
      bucketEnd: "2026-08-26T15:47:00.000Z",
      values: {
        request_count: 1114,
        cache_hit_rate: 19.3,
        cache_key_cardinality: 910,
        origin_request_count: 899,
        origin_error_rate: 13.38,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:47:00.000Z",
      bucketEnd: "2026-08-26T15:48:00.000Z",
      values: {
        request_count: 1102,
        cache_hit_rate: 18.15,
        cache_key_cardinality: 920,
        origin_request_count: 902,
        origin_error_rate: 13.79,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:48:00.000Z",
      bucketEnd: "2026-08-26T15:49:00.000Z",
      values: {
        request_count: 1086,
        cache_hit_rate: 18.69,
        cache_key_cardinality: 890,
        origin_request_count: 883,
        origin_error_rate: 12.25,
        response_latency_p99: 1806
      }
    },
    {
      bucketStart: "2026-08-26T15:49:00.000Z",
      bucketEnd: "2026-08-26T15:50:00.000Z",
      values: {
        request_count: 1118,
        cache_hit_rate: 18.43,
        cache_key_cardinality: 918,
        origin_request_count: 912,
        origin_error_rate: 14.49,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:50:00.000Z",
      bucketEnd: "2026-08-26T15:51:00.000Z",
      values: {
        request_count: 1057,
        cache_hit_rate: 17.88,
        cache_key_cardinality: 873,
        origin_request_count: 868,
        origin_error_rate: 11.16,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:51:00.000Z",
      bucketEnd: "2026-08-26T15:52:00.000Z",
      values: {
        request_count: 1087,
        cache_hit_rate: 17.2,
        cache_key_cardinality: 911,
        origin_request_count: 900,
        origin_error_rate: 13.8,
        response_latency_p99: 1804
      }
    },
    {
      bucketStart: "2026-08-26T15:52:00.000Z",
      bucketEnd: "2026-08-26T15:53:00.000Z",
      values: {
        request_count: 1108,
        cache_hit_rate: 18.59,
        cache_key_cardinality: 908,
        origin_request_count: 902,
        origin_error_rate: 13.72,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:53:00.000Z",
      bucketEnd: "2026-08-26T15:54:00.000Z",
      values: {
        request_count: 1117,
        cache_hit_rate: 17.1,
        cache_key_cardinality: 938,
        origin_request_count: 926,
        origin_error_rate: 15.76,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:54:00.000Z",
      bucketEnd: "2026-08-26T15:55:00.000Z",
      values: {
        request_count: 1097,
        cache_hit_rate: 18.96,
        cache_key_cardinality: 904,
        origin_request_count: 889,
        origin_error_rate: 12.67,
        response_latency_p99: 1810
      }
    },
    {
      bucketStart: "2026-08-26T15:55:00.000Z",
      bucketEnd: "2026-08-26T15:56:00.000Z",
      values: {
        request_count: 1123,
        cache_hit_rate: 19.06,
        cache_key_cardinality: 924,
        origin_request_count: 909,
        origin_error_rate: 14.16,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:56:00.000Z",
      bucketEnd: "2026-08-26T15:57:00.000Z",
      values: {
        request_count: 1102,
        cache_hit_rate: 15.88,
        cache_key_cardinality: 933,
        origin_request_count: 927,
        origin_error_rate: 16.06,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:57:00.000Z",
      bucketEnd: "2026-08-26T15:58:00.000Z",
      values: {
        request_count: 1096,
        cache_hit_rate: 17.52,
        cache_key_cardinality: 914,
        origin_request_count: 904,
        origin_error_rate: 14.05,
        response_latency_p99: 1807
      }
    },
    {
      bucketStart: "2026-08-26T15:58:00.000Z",
      bucketEnd: "2026-08-26T15:59:00.000Z",
      values: {
        request_count: 1117,
        cache_hit_rate: 17.64,
        cache_key_cardinality: 937,
        origin_request_count: 920,
        origin_error_rate: 15.22,
        response_latency_p99: 1808
      }
    },
    {
      bucketStart: "2026-08-26T15:59:00.000Z",
      bucketEnd: "2026-08-26T16:00:00.000Z",
      values: {
        request_count: 1116,
        cache_hit_rate: 19.8,
        cache_key_cardinality: 897,
        origin_request_count: 895,
        origin_error_rate: 12.99,
        response_latency_p99: 1806
      }
    }
  ]
};

export const deploymentMarkers = [
  {
    version: "catalog-edge-v42",
    at: "2026-08-26T14:18:00.000Z"
  }
] as const;
